In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import scrapbook as sb 
import pandas as pd
import numpy as np 
import seaborn as sns 
import numpy as np
from statistics import mean, median
import matplotlib.pyplot as plt

In [3]:
book = sb.read_notebooks("./GAN_Output")
gan_data = []
gan_mse = []
for nb in book.notebooks:
    metrics = nb.scraps['GAN_1 Metrics'].data
    for i in range(1000):
        gan_mse.append(metrics[0][i])
    nbList = [nb.scraps['GAN Model MSE'].data,
              nb.scraps['GAN Model MAE'].data,
              nb.scraps['GAN Model Euclidean distance'].data,
              nb.scraps['GAN Model Manhattan Distance'].data]        
    gan_data.append(nbList)
    
df = pd.DataFrame(gan_data, columns = ['MSE','MAE','Euclidean Distance','Manhattan Distance'])
display(df.style)
print("MEDIAN:")
print(df.median(axis = 0))
gan_data = np.array(gan_data)
gan_median = median(gan_data[:,1])

MEDIAN:
MSE                     0.021890
MAE                     0.116188
Euclidean Distance      4.677363
Manhattan Distance    116.188472
dtype: float64

In [4]:
book = sb.read_notebooks("./Output_B")
abc_mae = []
abc_mae_skip = []
abc_mae_mean = []
abc_mae_skip_mean = []
abc_weights = []
prior_model = []
abc_pre_generator = []

for nb in book.notebooks:
    metrics1 = np.array(nb.scraps['ABC_GAN_1 Metrics'].data)
    metrics3 = np.array(nb.scraps['ABC_GAN_3 Metrics'].data)    
    #Divide data according to parameters 
    for j in range(100):
        abc_mae.append(metrics1[1,j])
        abc_mae_skip.append(metrics3[1,j])
    abc_weights.append(nb.scraps['Skip Connection Weight'].data)
    prior_model.append(nb.scraps['Prior Model MAE'].data)
    abc_pre_generator.append(nb.scraps['Pre-generator MAE'].data)
    abc_mae_skip_mean.append(mean(metrics3[1,:]))
    abc_mae_mean.append(mean(metrics1[1,:]))

In [5]:
data = []
data_median_stats = []
for j in range(len(abc_weights)):
    data.append([prior_model[j],
                    abc_pre_generator[j],abc_weights[j],abc_mae_mean[j],abc_mae_skip_mean[j]])

df = pd.DataFrame(data, columns = ['Baseline','Prior Model','Weight','ABC_GAN','Skip_GAN'])
data_median_stats = [gan_median,df['Baseline'].median(),df['Prior Model'].median(), df['ABC_GAN'].median(), df['Skip_GAN'].median(),
                    df['Weight'].median()]            
df

    Baseline  Prior Model    Weight   ABC_GAN   Skip_GAN
0  13.546561    13.560030  0.000000  6.055869  13.540159
1  13.546561    13.591385  0.000000  1.377813  13.488199
2  13.546561    13.583307  0.064321  2.086893   7.022256
3  13.546561    13.574031  0.158704  2.128897   4.085192
4  13.546561    13.563138  0.000000  1.491501  13.704691
5  13.546561    13.582231  0.086598  1.485360   7.492197
6  13.546561    13.565276  0.000000  1.854673  13.079328
7  13.546561    13.579877  0.082608  2.268575   3.217496
8  13.546561    13.556756  0.220040  1.724187   1.667382
9  13.546561    13.571474  0.000000  1.430494  14.060422

In [6]:
data_median_stats = np.reshape(data_median_stats,(1,6))
median_output = pd.DataFrame(data_median_stats,columns=['GAN','Baseline','Prior Model','ABC_GAN','Skip_GAN','Weight'])
median_output.head()

        GAN   Baseline  Prior Model  ABC_GAN   Skip_GAN   Weight
0  0.116188  13.546561    13.572752  1.78943  10.285762  0.03216