In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import scrapbook as sb 
import pandas as pd
import numpy as np 
import seaborn as sns 
import numpy as np
from statistics import mean, median
import matplotlib.pyplot as plt

In [3]:
book = sb.read_notebooks("./GAN_Output")
gan_data = []
gan_mse = []
for nb in book.notebooks:
    metrics = nb.scraps['GAN_1 Metrics'].data
    for i in range(1000):
        gan_mse.append(metrics[0][i])
    nbList = [nb.scraps['GAN Model MSE'].data,
              nb.scraps['GAN Model MAE'].data,
              nb.scraps['GAN Model Euclidean distance'].data,
              nb.scraps['GAN Model Manhattan Distance'].data]        
    gan_data.append(nbList)
    
df = pd.DataFrame(gan_data, columns = ['MSE','MAE','Euclidean Distance','Manhattan Distance'])
display(df.style)
print("MEDIAN:")
print(df.median(axis = 0))
gan_data = np.array(gan_data)
gan_median = median(gan_data[:,1])

MEDIAN:
MSE                   0.247696
MAE                   0.413211
Euclidean Distance    2.223535
Manhattan Distance    8.264218
dtype: float64

In [4]:
book = sb.read_notebooks("./Output")
abc_mae = []
abc_mae_skip = []
abc_mae_mean = []
abc_mae_skip_mean = []
abc_weights = []
prior_model = []
abc_pre_generator = []

for nb in book.notebooks:
    metrics1 = np.array(nb.scraps['ABC_GAN_1 Metrics'].data)
    metrics3 = np.array(nb.scraps['ABC_GAN_3 Metrics'].data)    
    #Divide data according to parameters 
    for j in range(100):
        abc_mae.append(metrics1[1,j])
        abc_mae_skip.append(metrics3[1,j])
    abc_weights.append(nb.scraps['Skip Connection Weight'].data)
    prior_model.append(nb.scraps['Prior Model MAE'].data)
    abc_pre_generator.append(nb.scraps['Pre-generator MAE'].data)
    abc_mae_skip_mean.append(mean(metrics3[1,:]))
    abc_mae_mean.append(mean(metrics1[1,:]))

In [5]:
data = []
data_median_stats = []
for j in range(len(abc_weights)):
    data.append([prior_model[j],
                    abc_pre_generator[j],abc_weights[j],abc_mae_mean[j],abc_mae_skip_mean[j]])

df = pd.DataFrame(data, columns = ['Baseline','Prior Model','Weight','ABC_GAN','Skip_GAN'])
data_median_stats = [gan_median,df['Baseline'].median(),df['Prior Model'].median(), df['ABC_GAN'].median(), df['Skip_GAN'].median(),
                    df['Weight'].median()]            
df

    Baseline  Prior Model    Weight   ABC_GAN  Skip_GAN
0  12.525862    12.717743  0.098048  0.429263  0.342131
1  12.525862    12.622709  0.688813  0.408822  0.426525
2  12.525862    12.488678  0.093354  0.337397  0.372786
3  12.525862    12.607941  0.095218  0.401077  0.376607
4  12.525862    12.571546  0.103351  0.459175  0.562027
5  12.525862    12.461485  0.103178  0.412505  0.423827
6  12.525862    12.430249  0.509300  0.434511  0.527440
7  12.525862    12.539352  0.112534  0.335835  0.311925
8  12.525862    12.604055  0.441607  0.397879  0.403875
9  12.525862    12.436196  0.428829  0.458142  0.449128

In [6]:
data_median_stats = np.reshape(data_median_stats,(1,6))
median_output = pd.DataFrame(data_median_stats,columns=['GAN','Baseline','Prior Model','ABC_GAN','Skip_GAN','Weight'])
median_output.head()

        GAN   Baseline  Prior Model   ABC_GAN  Skip_GAN    Weight
0  0.413211  12.525862    12.555449  0.410664  0.413851  0.107943